### ISSUE TITLE
Js not working

### ISSUE THREAD

**Issue by amaanabbasi** [amaanabbasi/amaanabbasi.github.io#1]
animate css animations are not working with the js code in the html file.

**Comment by amaanabbasi** [comment]
thank you, you just saved my day.

**Comment by xavierchanth** [comment]
Was this reopened by mistake? Is there supposed to be any animations that I missed or is it just the title?

**Comment by dagolinuxoid** [comment]
BTW. It's really painful to write vendor-prefixes in your stylesheet manually - don't do it :)
